name: build our image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and push the image
        run: |
          docker pull mark0815/domain_connect_dyndns_updater:latest || true
          docker buildx build --push \
            --tag mark0815/domain_connect_dyndns_updater:${{ github.sha }} \
            --tag mark0815/domain_connect_dyndns_updater:latest \
            --cache-from mark0815/domain_connect_dyndns_updater:latest \
            --platform linux/amd64,linux/arm64 .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/mark0815/domain_connect_dyndns_updater:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
